#ifndef MUSIC_H
#define MUSIC_H

#include "buzzer.h"


const bz_key track1_music[] = {H3, H2, H1, H2, H3, H3,H4, H3, H2, H2,
                               H3, H2, H1, H2, H3, H3,H4, H3, H2, H2,
                               H3, H2, H1, H2, H3, H3,H4, H3, H2, H2,
                               H3, H2, H1, H2, H3, H3, H4, H3, H2, M1, M2,
                               M3, M3, M2, M4, M3, M2, M2, M2, M1, M1, M4, M3, M2,
                               M2, M1, M2, M3, M3, STOP, STOP, M3, M5, H1,
                               M7, H1, M7, H1, M7, M6, M5, M5, M2, M4,
                               M4, M3, M3, L5, M4, M3, M2, M3, M5,
                               M1, M1, STOP,  M1, M1, M2, M1, M1, M5, M1,
                               M4, M3, M2, M1, M1, M1, M1, STOP, M1, M2,
                               M3, M3, M2, M4, M3, M2, M2, M2, M1, M4, M3, M2,
                               M2, M1, M2, M3, M3, STOP, STOP, M3, M5, H1,
                               M7, H1, M7, H1, M7, M6, M5, M5, M2, M4,
                               M4, M3, M3, M3, L5, M4, M3, M2,  M3, M5,
                               M1, M1, STOP, M1, M1, M2, M1, M1, M5, M1,
                               M4, M4, M4, M3, M2, M2, M1, M1, M1, STOP,
                               M6, M5, M5, M5, M4, M4, M3, M2, M2, M2, M5,
                               M5, M4, M4, M4, M4, M3, M2, M2, M1, M1, L7, M1, M1,
                               M6, M5, M5, M5, M4, M4, M3, M2, M2, M2, M3,
                               M4, M3, M3, M3, M3, M3, M2, M3, H2, H1, H1,  H1,
                               M7, M6, M6, M6, M6, STOP, M6, M6, M5, M4, M4,
                               M4, M3, M3, M4, M5, M5, STOP,
                               M3, M2, M3, M2, M3, M4, M5, M4, M5, M6, M6, M7, H1, H2, H1,
                               M5, M5, M5, M4, M4, M3, M4, M3, M5, M5,
                               M3, M2, M3, M2, M3, M5, M4, M5, M6, STOP, M6, M7, STOP, M3,
                               H3, H3, H3, H3, H4, H3, H2, H2, H1, M7, H1, M5, H1,
                               H2, H1, H1, H1, M5, H2, H1, H1, H1, M5, H1,
                               H2, H1, H1, H1, M5, H1, H2, H2, H3, H2, H1, H1,
                               M7, M6, M6, M6, M5, M5, M4, M4, M3, M2,
                               M3, STOP, M3, M4, M3, M4, M3, M2,
                               M1, STOP};
const bz_time track1_time[] = {QURATER, QUAVER, QURATER, QUAVER, QUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QURATER, QUAVER,
                               QURATER, QUAVER, QURATER, QUAVER, QUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QURATER, QUAVER,
                               QURATER, QUAVER, QURATER, QUAVER, QUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QURATER, QUAVER,
                               QURATER, QUAVER, QURATER, QUAVER, QUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QURATER, DEMIQUAVER,DEMIQUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, DEMIQUAVER, DEMIQUAVER,QUAVER, QUAVER, QUAVER,
                               QURATER, DEMIQUAVER, DEMIQUAVER, QURATER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER,QUAVER,
                               QURATER, QUAVER, QURATER, QUAVER, DEMIQUAVER, DEMIQUAVER, QURATER, QUAVER, QUAVER, QUAVER,
                               QURATER, QUAVER, QURATER,  QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER,
                               QURATER, QUAVER, QURATER, DEMIQUAVER, DEMIQUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER,
                               QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QURATER, DEMIQUAVER, DEMIQUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QURATER, DEMIQUAVER, DEMIQUAVER, QURATER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QURATER, QUAVER, QURATER, QUAVER, DEMIQUAVER, DEMIQUAVER, QURATER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER,
                               QURATER, QUAVER, QURATER, DEMIQUAVER, DEMIQUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER,
                               QUAVER, DEMIQUAVER, DEMIQUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QUAVER, QUAVER, HALF, QURATER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER,
                               QUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, DEMIQUAVER, DEMIQUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER,
                               QUAVER, DEMIQUAVER, DEMIQUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, DEMIQUAVER, DEMIQUAVER,
                               QURATER, QUAVER, DEMIQUAVER, DEMIQUAVER, QURATER, HALF, QURATER,
                               DEMIQUAVER, DEMIQUAVER, DEMIQUAVER, DEMIQUAVER, DEMIQUAVER, DEMIQUAVER, QURATER, DEMIQUAVER, DEMIQUAVER, QURATER, DEMIQUAVER, DEMIQUAVER, QURATER, DEMIQUAVER, DEMIQUAVER,
                               QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, DEMIQUAVER, DEMIQUAVER, QURATER, QUAVER,
                               DEMIQUAVER, DEMIQUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QURATER, DEMIQUAVER, DEMIQUAVER,QURATER, DEMIQUAVER, DEMIQUAVER, QURATER, DEMIQUAVER, DEMIQUAVER,
                               QUAVER, QUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QUAVER, QUAVER, QURATER, DEMIQUAVER, DEMIQUAVER, QURATER, DEMIQUAVER, DEMIQUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, DEMIQUAVER, DEMIQUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, DEMIQUAVER, DEMIQUAVER, QUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER,
                               HALF, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               WHOLE, WHOLE};
const bz_nop track1_nop[] = {NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP, CONTINUE, NOP,
                             NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP, CONTINUE, NOP,
                             NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP, CONTINUE, NOP,
                             NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, CONTINUE, NOP, CONTINUE, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             CONTINUE, NOP, NOP,  NOP, NOP, NOP,NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, CONTINUE, NOP, CONTINUE, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             CONTINUE, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP,
                             NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,NOP, NOP,
                             CONTINUE, NOP, NOP, NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, CONTINUE, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP};

#endif //MUSIC_H
