#ifndef TRACK2_H
#define TRACK2_H

#include "buzzer.h"


const bz_key track2_music[] = {M5, STOP, M1,  L6, L7,
                               M5, M2, M5, M1, M3, M1, M4, M4,
                               L1, L5, M1, M2, M1, L4, L1, M1, M2, M1,
                               L1, L5, M1, M2, M1, L4, L1, M1, M2, L4,
                               L1, L5, M1, L5, L4, L1, M2, L4,
                               L1, L5, M1, L5, M1, M1, L5, M3,
                               L4, L1, M1, M5, M3, L5, L2, L7, M3, M2,
                               M1, L1, L5, M1, L1, M1, L1, L5, M3,
                               L4, L1, L6, L7, L2, L6, L6, L2, L5,
                               L4, L1, M1, L5, L2, L1, L5, M1, M2, M1, L5,
                               L1, L5, M1, L5, L4, L1, M2, L4,
                               L1, L5, M1, L5, L3, M1, L5, M3,
                               L4, L1, M1, M5, M3, L5, L2, L7, M3, M2,
                               L3, L1, L5, M1, L1, L3, L1, L5, M3,
                               L4, L1, L6, L7, L2, L6, L6, L2, L5,
                               L4, L1, M1, L5, L2, L1, L5, M1, M3, M3,
                               L4, STOP, L5, STOP,
                               L3, STOP, L3, STOP,
                               M1, STOP, L5, STOP,
                               M2, STOP, M5, M3, M1, M2, M1, L5,
                               L1, L1, L4, M3, M1, L4, L4, L1, L4, M3, M1, L4,
                               L2, L2, L5, M2, L5, L2, L5, L2, L5, M2, L5, L2,
                               L1, L5, M3, M2, L5, L4, L1, M4, L6, L4,
                               L5, L3, L5, M2, L5, L3, L6, L3, L6, M3, M2, L5,
                               L1, L5, M3, M2, L5, L4, L1, M1, L7, L3, M3,
                               L5, L3, L7, M5, L7, L6, L3, M3, M2, L5,
                               L4, L1, M1, M4, M1, L4, L5, L2, M2, M5, M2, L5,
                               L5, L1, L5, M3, M1, L5, L1, M1, M3, M5, M1, L5,
                               L4, L1, M1, M4, M1, L4, L5, L2, L7, M2, L7, L5,
                               L1, L5, M1, M2, M1, L5, L4, L6, M1, L5, L2, L7,
                               L5, M1, L1, L5, M2, M1,};
const bz_time track2_time[] = {HALF, QURATER, HALF, QUAVER, QUAVER,
                               QUAVER, QURATER, QURATER, QUAVER, QURATER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER,
                               QUAVER, QURATER, QURATER, QUAVER, QUAVER, QURATER, QURATER, QUAVER,
                               QUAVER, QURATER, QURATER, QUAVER, QUAVER, QURATER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QURATER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QURATER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QURATER, QURATER, QUAVER, QUAVER, QURATER, QURATER, QUAVER,
                               QUAVER, QURATER, QURATER, QUAVER, QURATER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QURATER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QURATER, QUAVER, QURATER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER,
                               HALF, QURATER, HALF, QURATER,
                               HALF, QURATER, HALF, QURATER,
                               HALF, QURATER, HALF, QURATER,
                               HALF, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QURATER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QURATER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER, QUAVER,
                               QUAVER, DEMIQUAVER, DEMIQUAVER, QUAVER, QURATER, QUAVER,};
const bz_nop track2_nop[] = {NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP,NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP, NOP, NOP, CONTINUE, NOP,
                             NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP, NOP, NOP,NOP, NOP,
                             NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP, NOP, NOP,NOP, NOP,
                             NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP, NOP, NOP,NOP, NOP,
                             NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP, NOP, NOP,NOP,
                             NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP, NOP, NOP,
                             NOP, NOP,NOP, NOP, NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP,
                             NOP, NOP,NOP, NOP, NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP,
                             NOP, NOP,NOP, NOP, NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP,
                             NOP, NOP,NOP, NOP, NOP, NOP, NOP, NOP,NOP, NOP, NOP, NOP,
                             NOP, NOP, NOP, NOP, NOP, NOP,};

#endif //TRACK2_H
